### PR TITLE
Fix file download

### PR DESCRIPTION
**Pull request by tristan0x**
downloadUrl needs to be updated because not valid more than 8 hours.

### CODE REVIEW

**Comment by tristan0x** [comment]
@tsanch3z Please review

**Comment by tristan0x** [comment]
@tuxnco please review

**Comment by tsanch3z** [comment]
It looks good

**Comment by tristan0x** [comment]
@tuxnco thx!

**Comment by tristan0x** [comment]
@tsanch3z thx dude!

**Pull request merged**
